<?xml version="1.0" encoding="utf-8"?><Database Name="TaskTracker" Class="TaskTrackerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\TaskTracker.mdf;Integrated Security=True" SettingsObjectName="Task_Tracker.Properties.Settings" SettingsPropertyName="TaskTrackerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clients" Member="Clients">
    <Type Name="Client">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FamilyName" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GivenNames" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ABN" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ContactNumber" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Email" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Client_Project" Member="Projects" ThisKey="ID" OtherKey="ClientID" Type="Project" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Task">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaskName" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Priority" Type="System.String" DbType="Varchar(10)" CanBeNull="false" />
      <Column Name="CompletionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Task_DeveloperIterationTask" Member="DeveloperIterationTasks" ThisKey="ID" OtherKey="TaskID" Type="DeveloperIterationTask" />
      <Association Name="Task_IterationTask" Member="IterationTasks" ThisKey="ID" OtherKey="TaskID" Type="IterationTask" />
      <Association Name="Project_Task" Member="Project" ThisKey="ProjectID" OtherKey="ID" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeveloperIterationTasks" Member="DeveloperIterationTasks">
    <Type Name="DeveloperIterationTask">
      <Column Name="DeveloperID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TaskID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IterationID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Task_DeveloperIterationTask" Member="Task" ThisKey="TaskID" OtherKey="ID" Type="Task" IsForeignKey="true" />
      <Association Name="Developer_DeveloperIterationTask" Member="Developer" ThisKey="DeveloperID" OtherKey="ID" Type="Developer" IsForeignKey="true" />
      <Association Name="Iteration_DeveloperIterationTask" Member="Iteration" ThisKey="IterationID" OtherKey="ID" Type="Iteration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Developers" Member="Developers">
    <Type Name="Developer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FamilyName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="GivenNames" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ContactNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Developer_DeveloperIterationTask" Member="DeveloperIterationTasks" ThisKey="ID" OtherKey="DeveloperID" Type="DeveloperIterationTask" />
    </Type>
  </Table>
  <Table Name="dbo.Iterations" Member="Iterations">
    <Type Name="Iteration">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Iteration_DeveloperIterationTask" Member="DeveloperIterationTasks" ThisKey="ID" OtherKey="IterationID" Type="DeveloperIterationTask" />
      <Association Name="Iteration_IterationTask" Member="IterationTasks" ThisKey="ID" OtherKey="IterationID" Type="IterationTask" />
      <Association Name="Project_Iteration" Member="Project" ThisKey="ProjectID" OtherKey="ID" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IterationTasks" Member="IterationTasks">
    <Type Name="IterationTask">
      <Column Name="TaskID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IterationID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlannedStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PlannedCompletionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Iteration_IterationTask" Member="Iteration" ThisKey="IterationID" OtherKey="ID" Type="Iteration" IsForeignKey="true" />
      <Association Name="Task_IterationTask" Member="Task" ThisKey="TaskID" OtherKey="ID" Type="Task" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Project">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectName" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CompletionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="Varchar(20)" CanBeNull="false" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Project_Task" Member="Tasks" ThisKey="ID" OtherKey="ProjectID" Type="Task" />
      <Association Name="Project_Iteration" Member="Iterations" ThisKey="ID" OtherKey="ProjectID" Type="Iteration" />
      <Association Name="Client_Project" Member="Client" ThisKey="ClientID" OtherKey="ID" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
</Database>